name: Build desired state

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  insert_JSON_staging_data:
    runs-on: APP_1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: I should run 1st
        run: echo "I ran 1st!"

  insert_vcenter_objects:
    runs-on: APP_1
    steps:
      - name: I should run 2nd
        run: echo "I ran 2nd"
      
  compare_staging_data:
    runs-on: APP_1
    needs:
      - insert_JSON_staging_data
      - insert_vcenter_objects
    steps:
      - name: I should run 3rd
        run: echo "I run 3rd"
  update_desired_state:
    runs-on: APP_1
    needs:
      - compare_staging_data
    steps:
      - name: I should run 4th
        run: echo "I run 4th"
  import_desired_state:
    runs-on: APP_1
    needs:
      - update_desired_state
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          APPROVER_NAME: ${{ github.actor }}
          COMMITER_NAME: ${{ github.actor }}
        run: echo "$GITHUB_CONTEXT"
      - name: Restore PR Number from Cache
        uses: actions/cache/restore@v4
        with:
          path: pr_num.txt
          key: pr-number-${{ github.sha }}

      # Read it directly into your environment
      - name: Read the Variable
        run: |
          if [ -f pr_num.txt ]; then
            PR_NUMBER=$(cat pr_num.txt)
            echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
            echo "Successfully loaded PR Number: $PR_NUMBER"
            echo "Approver name: $env:APPROVER_NAME" 
            echo "Commiter name: $env:COMMITER_NAME" 
          else
            echo "No cached PR number found for this commit."
          fi
