name: Build desired state

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  insert_JSON_staging_data:
    runs-on: APP_1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: I should run 1st
        run: echo "I ran 1st!"

  insert_vcenter_objects:
    runs-on: APP_1
    steps:
      - name: I should run 2nd
        run: echo "I ran 2nd"
      
  compare_staging_data:
    runs-on: APP_1
    needs:
      - insert_JSON_staging_data
      - insert_vcenter_objects
    steps:
      - name: I should run 3rd
        run: echo "I run 3rd"
  update_desired_state:
    runs-on: APP_1
    needs:
      - compare_staging_data
    steps:
      - name: I should run 4th
        run: echo "I run 4th"
  import_desired_state:
    runs-on: APP_1
    needs:
      - update_desired_state
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          APPROVER_NAME: ${{ github.actor }}
          COMMITER_NAME: ${{ github.event.commits.author.name }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "Approver name: $APPROVER_NAME" 
          echo "Commiter name: $COMMITER_NAME" 
      - name: Read PR Number Locally
        run: |
          FILE_PATH="/tmp/pr_number.txt"
          if [ -f "$FILE_PATH" ]; then
            PR_NUMBER=$(cat "$FILE_PATH")
            echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
            echo "Found PR Number: $PR_NUMBER"

            # Optional: clean up the file now that you're done with it
            rm "$FILE_PATH"
          else
            echo "No local file found for this commit SHA."
          fi
