name: test

on: push

jobs:
  test-job:
    runs-on: APP_1
    steps:
      - run: echo "It works!"
  test-job2:
    runs-on: APP_1
    steps:
      - run: echo "It really works!"
  test-job3:
    runs-on: APP_1
    needs:
      - test-job
      - test-job2
    steps:
      - run: echo "It really works!"
  test-job4:
    runs-on: APP_1
    needs:
      - test-job
      - test-job2
    steps:
      - run: echo "It really works!"