name: Precheck
on:
  pull_request:
    branches: [ main ]

jobs:
  Check_Duplicates:
    name: Check_Duplicates
    runs-on: APP_1
    
    steps:
      - name: Checkout_repo
        uses: actions/checkout@v4

      - name: Get changed files
        run: |
          
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep '\.json$' || true)
          CHANGED_FILES=$( sed -e 's/.json/.json"/g' -e 's/JSON/"JSON/g' <<< $CHANGED_FILES)
          $GITHUB_WORKSPACE= ${{ github.workspace }}
          RAW_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          echo $CHANGED_FILES
          echo $RAW_FILES
          echo $GITHUB_WORKSPACE
          

      - name: Check_user_duplicates
        run: |

          USER_DUPLICATES=$(jq -n '[ inputs as $file | $file | {Role: .Name, FileName: input_filename, assignments: .assignments[]} | {Role, FileName, Object: .assignments.object, User: .assignments."user-or-group"[]} ] | group_by(.Object, .User) | .[] | select(length>1) |  .[] + { User_duplicate: "True"}' /srv/actions-runner/_work/LAB/LAB/JSON/*.json)
          
          if [ -n "$USER_DUPLICATES" ]; then
            echo "❌ Duplicates discovered:"
            echo "$USER_DUPLICATES"
            exit 1
          else
            echo "✅ No duplicates found."
            exit 0
          fi
