name: Precheck
on:
  pull_request:
    branches: [ main ]

jobs:
  Check_Duplicates:
    name: Check_Duplicates
    runs-on: APP_1
    
    steps:
      - name: Checkout_repo
        uses: actions/checkout@v4
      
      - name: Check_object_duplicates
        run: |

          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep '\.json$' || true)
          FINAL_FILES=()

          while IFS= read -r line; do
              if [[ -n "$line" ]]; then
          
                  CLEAN_PATH=$(echo "$line" | xargs)
                  echo $CLEAN_PATH
                  FINAL_FILES+=("$GITHUB_WORKSPACE/$CLEAN_PATH")
                  echo ${FINAL_FILES[@]}
              fi
          done
          
          OBJECT_DUPLICATES=$(jq -n '[ inputs as $file | $file | {Role: .Name, FileName: input_filename, assignments: .assignments[]} | {Role, FileName, Object: .assignments.object} ] | group_by(.Object, .FileName) | .[] | select(length>1) | .[] + { Object_duplicate: "True"}'  "${FINAL_FILES[@]}")
          
          if [ -n "$OBJECT_DUPLICATES" ]; then
            echo "❌ Duplicates discovered:"
            echo "$OBJECT_DUPLICATES"
            exit 1
          else
            echo "✅ No duplicates found."
            exit 0
          fi
          
      - name: Check_user_duplicates
        run: |

          USER_DUPLICATES=$(jq -n '[ inputs as $file | $file | {Role: .Name, FileName: input_filename, assignments: .assignments[]} | {Role, FileName, Object: .assignments.object, User: .assignments."user-or-group"[]} ] | group_by(.Object, .User) | .[] | select(length>1) |  .[] + { User_duplicate: "True"}' /srv/actions-runner/_work/LAB/LAB/JSON/*.json)
          
          if [ -n "$USER_DUPLICATES" ]; then
            echo "❌ Duplicates discovered:"
            echo "$USER_DUPLICATES"
            exit 1
          else
            echo "✅ No duplicates found."
            exit 0
          fi
